In [2]:
import numpy as np

In [4]:
A = np.array([[1, 1, 1, 1],[2, -1, 3, 4],[-3, 2, -2, 5],[1, -1, 4, -1]])
B = np.array([10, 8, -3, 5])

ans = np.linalg.solve(A,B)
ans

array([3.44339623, 4.69811321, 1.62264151, 0.23584906])

In [8]:
A = np.array([[2100, 1500], 
              [-600, 900]])

B = np.array([12, 15])

I2, I3 = np.linalg.solve(A, B)
I1 = I2 + I3


print(f"I1 = {I1:.4f} A")
print(f"I2 = {I2:.4f} A")
print(f"I3 = {I3:.4f} A")


I1 = 0.0097 A
I2 = -0.0042 A
I3 = 0.0139 A


In [5]:
A = np.array([[2, 1, 3],
              [1, 2, 1],
              [3, 1, 2]])


A_inv = np.linalg.inv(A)


print(A_inv)

[[-0.375 -0.125  0.625]
 [-0.125  0.625 -0.125]
 [ 0.625 -0.125 -0.375]]
